[package]
name = "external_dns_host_webhook_provider"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5.17", features = ["derive", "env"] }
salvo = "0.71.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1", features = ["full" ] }
