name: Delete Image on Branch Deletion

on:
  delete:
    branches-ignore: [ "latest" ]

env:
    DOCKER_REPOSITORY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
      

jobs:
  delete-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check if ref is a branch
        if: startsWith(github.event.ref, 'refs/heads/')
        run: echo "Branch ${GITHUB_REF} has been deleted."
     
      - name: Login to registry ${{ env.DOCKER_REPOSITORY }}
        uses: docker/login-action@v3  # https://github.com/docker/login-action
        with:
            registry: ${{ env.DOCKER_REPOSITORY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Delete Docker Image
        run: |
          IMAGE_NAME=<image-name>:$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')
          echo "Deleting image $IMAGE_NAME"
          docker rmi ${IMAGE_NAME}
        # env:
        #   DOCKER_REPOSITORY: <your-docker-repository>
