name: Build and test rust application

on:
  workflow_dispatch: # Permet le déclenchement manuel du workflow
  push:
    branches-ignore: [ "latest" ]
    paths:
      - 'Dockerfile'
      - 'src/**.rs'
      - 'Cargo.lock'
      - 'Cargo.toml'
  
env:
  DOCKER_REPOSITORY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # https://github.com/docker/setup-qemu-action
      - 
        name: Set up Docker
        uses: docker/setup-buildx-action@v3  # https://github.com/docker/setup-buildx-action
      - 
        name: Login to registry ${{ env.DOCKER_REPOSITORY }}
        uses: docker/login-action@v3  # https://github.com/docker/login-action
        with:
          registry: ${{ env.DOCKER_REPOSITORY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - 
        name: Normalize tag
        id: tag
        run: echo "new_tag=$(echo '${{ github.ref_name }}' | tr '/' '-')" >> "$GITHUB_OUTPUT"
      - 
        name: Build and push ${{ github.repository }}:${{ steps.tag.outputs.new_tag }}
        uses: docker/build-push-action@v6  # https://github.com/docker/build-push-action
        with:
          push: true
          tags: ${{ env.DOCKER_REPOSITORY }}/${{ github.repository }}:${{ steps.tag.outputs.new_tag }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
