name: Build and test rust application

on:
  push:
    branches-ignore: [ "latest" ]
    paths:
      - 'src/**.rs'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'Dockerfile'

env:
  DOCKER_REPOSITORY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # https://github.com/docker/setup-qemu-action
      - 
        name: Set up Docker
        uses: docker/setup-buildx-action@v3  # https://github.com/docker/setup-buildx-action
      - 
        name: Login to registry ${{ env.DOCKER_REPOSITORY }}
        uses: docker/login-action@v3  # https://github.com/docker/login-action
        with:
          registry: ${{ env.DOCKER_REPOSITORY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push ${{ github.repository }}:${{ github.ref }}
        uses: docker/build-push-action@v6  # https://github.com/docker/build-push-action
        with:
          push: true
          tags: ${{ github.repository }}:${{ github.ref }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max


