name: Create release

on:
  workflow_dispatch: # Permet le déclenchement manuel du workflow
  pull_request:
    types:
      - closed
    branches: [ "latest" ]
    paths:
      - 'src/**.rs'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'Dockerfile'

env:
  REGISTRY: ghcr.io

jobs:

  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Push Tag with new version
        if: github.ref_type != 'tag'
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2 # https://github.com/mathieudutour/github-tag-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Create a GitHub release
        uses: softprops/action-gh-release@v2 # https://github.com/ncipollo/release-action
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ github.repository }} ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # https://github.com/docker/setup-qemu-action
      - 
        name: Set up Docker
        uses: docker/setup-buildx-action@v3  # https://github.com/docker/setup-buildx-action
      - 
        name: Login to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3  # https://github.com/docker/login-action
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract Docker metadata from ${{ env.REGISTRY }}/${{ github.repository }}
        id: metadata
        uses: docker/metadata-action@v5  # https://github.com/docker/metadata-action
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
      - 
        name: Build and push ${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }} (${{ github.ref }})
        uses: docker/build-push-action@v6  # https://github.com/docker/build-push-action
        with:
          push: true
          platforms: linux/amd64
          tags: |
            ${{ github.repository }}:${{ github.ref }}
            ${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }}
          annotations: ${{ steps.metadata.outputs.annotations }}
          labels: ${{ steps.metadata.outputs.labels }}
          sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max


